name: Build and Push to ECR

on:
  push:
    branches:
      - dev
      - qa
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

	- name: Set ECR repository based on branch
      id: set-repo
	  run: |
	    BRANCH_NAME="${GITHUB_REF##*/}"
        if [ "$BRANCH_NAME" = "dev" ]; then
          echo "repo_name=${{ secrets.ECR_REPO_DEV }}" >> $GITHUB_OUTPUT
        elif [ "$BRANCH_NAME" = "qa" ]; then
          echo "repo_name=${{ secrets.ECR_REPO_QA }}" >> $GITHUB_OUTPUT
        elif [ "$BRANCH_NAME" = "master" ]; then
          echo "repo_name=${{ secrets.ECR_REPO_MASTER }}" >> $GITHUB_OUTPUT
        else
          echo "Unsupported branch: $BRANCH_NAME"
        exit 1
        fi
    - name: Build Docker image
      run: |
        echo "Building image: ${{ secrets.ECR_REGISTRY }}/$REPO_NAME:$IMAGE_TAG .
        docker build -t ${{ secrets.ECR_REGISTRY }}/$REPO_NAME:$IMAGE_TAG .

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/$REPO_NAME:$IMAGE_TAG
